logging: 
  level: 
    '[de.codecentric.boot.admin.server.web.client]': debug
    '[de.codecentric.boot.admin]': debug


spring:
  boot:
    admin:
      discovery:
        ignored-services: nothing-for-now
      notify:
        slack:
          webhook-url: https://hooks.slack.com/services/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
          
eureka:
  instance:
    appname: spring-boot-admin-server
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      user:
        name: "thirumal"
        password: "thirumal"
    preferIpAddress: true
  client:
    region: default
    enabled: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    service-url:
      defaultZone: http://thirumal:thirumal@localhost:8761/eureka/,http://thirumal:thirumal@localhost:8762/eureka/,http://thirumal:thirumal@localhost:8763/eureka/
      