logging: 
  level: 
    '[de.codecentric.boot.admin.server.web.client]': error
    '[de.codecentric.boot.admin]': error

spring:
  boot:
    admin: 
      notify: 
        ms-teams:
          enabled: true
          webhook-url: https://enkindle.webhook.office.com/webhookb2/a88465ce-b74c-4d74-8f48-dc97a0662bb1@8f8998d2-4e65-4757-8e6e-be97a171a01d/IncomingWebhook/2532e1e3c18b4a289a99c96259bfb123/54b0c17e-7e1d-4e85-9b20-de0cca21b654
          
eureka:
  instance:
    appname: spring-boot-admin-server
    hostname: localhost
  client:
    service-url:
      defaultZone: http://thirumal:thirumal@172.31.17.33:8761/eureka/,http://thirumal:thirumal@172.31.17.211:8762/eureka/,http://thirumal:thirumal@172.31.19.111:8763/eureka/
      