logging: 
  level: 
    '[de.codecentric.boot.admin.server.web.client]': debug
    '[de.codecentric.boot.admin]': debug


spring:
  boot:
    admin:
      discovery:
        ignored-services: nothing-for-now
      notify:
        slack:
          webhook-url: https://hooks.slack.com/services/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
          
eureka:
  instance:
    appname: spring-boot-admin-server
    hostname: localhost
  client:
    service-url:
      defaultZone: http://thirumal:thirumal@localhost:8761/eureka/,http://thirumal:thirumal@localhost:8762/eureka/,http://thirumal:thirumal@localhost:8763/eureka/
      