logging: 
  level: 
    '[de.codecentric.boot.admin.server.web.client]': debug
    '[de.codecentric.boot.admin]': debug


spring:
  boot:
    admin:
      notify:
        slack:
          webhook-url: https://hooks.slack.com/services/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
          
eureka:
  instance:
    appname: spring-boot-admin-server
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
  client:
    region: default
    enabled: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    service-url:
      defaultZone: http://thirumal:thirumal@localhost:8761/eureka/
      